---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

verifier:
  name: inspec
  sudo: true

platforms:
- name: ubuntu-12.04
  driver:
    image: ubuntu:12.04
- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04
- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
- name: centos-6.6
  driver:
    image: centos:6.6
- name: centos-6.7
  driver:
    image: centos:6.7
- name: centos-6.8
  driver:
    image: centos:6.8
- name: centos-7
  driver:
    image: centos:7
    privileged: true
    run_command: /usr/sbin/init
- name: centos-7.2
  driver:
    image: centos:7.2.1511
    privileged: true
    run_command: /usr/sbin/init
- name: debian-7
  driver:
    image: debian:7
- name: debian-8
  driver:
    image: debian:8

suites:
  - name: default
    verifier:
      inspec_tests:
        - path: .
